### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by qouteall** [SuperCoder7979/databreaker#6]
```
[21:53:46] [Server thread/ERROR] (Minecraft) Couldn't load chunk [-15, 31]
 java.util.NoSuchElementException: null
	at it.unimi.dsi.fastutil.ints.Int2ObjectAVLTreeMap.firstIntKey(Int2ObjectAVLTreeMap.java:981) ~[fastutil-8.2.1.jar:?]
	at com.mojang.datafixers.DataFixerUpper.getLowestSchemaSameVersion(DataFixerUpper.java:101) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.DataFixerUpper.getSchema(DataFixerUpper.java:93) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.DataFixerUpper.getType(DataFixerUpper.java:97) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.DataFixerUpper.update(DataFixerUpper.java:83) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.nbt.NbtHelper.update(NbtHelper.java:520) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.nbt.NbtHelper.update(NbtHelper.java:273) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.world.storage.VersionedChunkStorage.updateChunkTag(VersionedChunkStorage.java:43) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.getUpdatedChunkTag(ThreadedAnvilChunkStorage.java:832) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17256(ThreadedAnvilChunkStorage.java:491) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1764) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:136) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.executeTask(ServerChunkManager.java:517) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:109) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.runTask(ServerChunkManager.java:525) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.server.world.ServerChunkManager.executeQueuedTasks(ServerChunkManager.java:268) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:737) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:723) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:119) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:709) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.server.MinecraftServer.prepareStartRegion(MinecraftServer.java:476) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:315) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.setupServer(IntegratedServer.java:63) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:639) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:224) ~[minecraft-1.16.2-projectmapped-net.fabricmc.yarn-1.16.2+build.26-v2.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by qouteall** [comment]
Now it even crashes
```
 net.minecraft.util.crash.CrashException: Ticking memory connection
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:153) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:801) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:81) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:659) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:224) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.util.NoSuchElementException
	at it.unimi.dsi.fastutil.ints.Int2ObjectAVLTreeMap.firstIntKey(Int2ObjectAVLTreeMap.java:981) ~[fastutil-8.2.1.jar:?]
	at com.mojang.datafixers.DataFixerUpper.getLowestSchemaSameVersion(DataFixerUpper.java:101) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.DataFixerUpper.getSchema(DataFixerUpper.java:93) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.DataFixerUpper.getType(DataFixerUpper.java:97) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.DataFixerUpper.update(DataFixerUpper.java:83) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.nbt.NbtHelper.update(NbtHelper.java:520) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.nbt.NbtHelper.update(NbtHelper.java:273) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.stat.ServerStatHandler.parse(ServerStatHandler.java:94) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.stat.ServerStatHandler.<init>(ServerStatHandler.java:50) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.server.PlayerManager.createStatHandler(PlayerManager.java:810) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.server.network.ServerPlayerEntity.<init>(ServerPlayerEntity.java:180) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.server.PlayerManager.createPlayer(PlayerManager.java:441) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler.java:112) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler.java:59) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.network.ClientConnection.tick(ClientConnection.java:216) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:150) ~[minecraft-1.16.3-projectmapped-net.fabricmc.yarn-1.16.3+build.28-v2.jar:?]
	... 6 more
```
